contact_links:
  - name: General questions
    url: https://github.com/mhanki/Clean-React/discussions
    about: If you have any general questions about the project, please add them in the discussion tab.
